---
- name: "Настройка k3s Master Node"
  hosts: k3s_masters
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: "Обновление системы"
      apt:
        upgrade: dist
        update_cache: yes

  roles:
    - role: k3s_master

  post_tasks:
    - name: "Проверка состояния кластера"
      command: kubectl get nodes -o wide
      register: nodes
      changed_when: false

    - name: "Вывод информации о нодах"
      debug:
        var: nodes.stdout_lines 