replicaCount: 3

image:
  repository: your-registry/my-microservice
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPU: 80

service:
  type: ClusterIP
  port: 8000

config:
  kafka:
    bootstrapServers: kafka.kafka.svc.cluster.local:9092
    topic: my-service-events
  postgres:
    host: postgres-postgresql.postgres.svc.cluster.local
    port: 5432
    database: mydb
  minio:
    endpoint: minio.minio.svc.cluster.local:9000
    bucket: my-service-data

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

podSecurityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL 