apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafka.bootstrapServers }}
  KAFKA_TOPIC: {{ .Values.config.kafka.topic }}
  POSTGRES_HOST: {{ .Values.config.postgres.host }}
  POSTGRES_PORT: {{ .Values.config.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.config.postgres.database }}
  MINIO_ENDPOINT: {{ .Values.config.minio.endpoint }}
  MINIO_BUCKET: {{ .Values.config.minio.bucket }}
  LOG_LEVEL: "INFO"
  METRICS_PORT: "8000" 