apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.config.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.config.postgres.password | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.config.minio.accessKey | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.config.minio.secretKey | b64enc }} 